class Regex:

    NICKNAME = "^[a-zA-Z0-9_]*$"

class CommonQSS:
    
    NEUTRAL_COLOR = "555555"

    MAIN_BACKGROUND_COLOR = "0c0c0c"

class MainWindowSharedQSS:

    BACKGROUND_COLOR = CommonQSS.MAIN_BACKGROUND_COLOR

    COLOR = "f2f2f2"

class LoginWidgetSharedQSS:

    LINE_EDIT_BACKGROUND_COLOR = "cccccc"

    LINE_EDIT_COLOR = "000000"

    ENTER_BUTTON_TEXT_COLOR = CommonQSS.NEUTRAL_COLOR

class ChatWidgetSharedQSS:

    CONTACT_SEARCH_PLACEHOLDER_COLOR = CommonQSS.NEUTRAL_COLOR

    BACKGROUND_COLOR = CommonQSS.MAIN_BACKGROUND_COLOR

    SCROLLBAR_SHOWED_COLOR = CommonQSS.NEUTRAL_COLOR